# Generated by Django 4.2.16 on 2024-10-09 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galary',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='about',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='./about'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.faq_thumbnail'),
        ),
    ]
